apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-hpa
  template:
    metadata:
      labels:
        name: go-hpa
    spec:
      containers:
        - name: go
          image: diovanes/go-hpa
          ports:
            - containerPort: 8000

          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "100Mi"